# Basic Snort configuration for demo SOC portfolio
include classification.config
include reference.config

var HOME_NET any
var EXTERNAL_NET any

ipvar RULE_PATH ./rules

include $RULE_PATH/custom-rules.rules

output alert_fast: snort_alerts.txt
